apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-deployment
  labels:
    app: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems
  template:
    metadata:
      labels:
        app: ems
    spec:
      containers:
        - name: ems
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
