apiVersion: v1
kind: Service
metadata:
  name: ems-service
  labels:
    app: ems
spec:
  type: LoadBalancer
  selector:
    app: ems
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
